import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { homedir } from 'node:os'

export interface ProposalInput {
  skill: string
  problem: string
  proposedChange: string
  evidence: string[]
}

// SKILLSTATS_HOME overrides the state directory (hermetic tests, CI, custom setups).
export function proposalsDir(): string {
  const base = process.env.SKILLSTATS_HOME ?? join(homedir(), '.skill-analytics')
  return join(base, 'proposals')
}

// Writes a human-reviewable markdown proposal and returns its path.
// NEVER edits any SKILL.md — the improvement loop stays human-gated by design.
export function writeProposal(input: ProposalInput): string {
  const dir = proposalsDir()
  mkdirSync(dir, { recursive: true })
  const path = join(dir, `${slug(input.skill)}-${Date.now()}.md`)
  writeFileSync(path, render(input))
  return path
}

function render(input: ProposalInput): string {
  const evidence = input.evidence.length
    ? input.evidence.map((e) => `- ${e}`).join('\n')
    : '- (none supplied)'
  return [
    `# Skill improvement proposal: ${input.skill}`,
    '',
    `> Generated by skill-stats on ${new Date().toISOString()}.`,
    '> This is a proposal only. No SKILL.md was modified. Review and apply by hand.',
    '',
    '## Problem',
    '',
    input.problem.trim(),
    '',
    '## Proposed change',
    '',
    input.proposedChange.trim(),
    '',
    '## Evidence',
    '',
    evidence,
    '',
  ].join('\n')
}

function slug(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/^-+|-+$/g, '') || 'skill'
}
